# Generated by Django 4.0.6 on 2022-07-15 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_orderhistory_user_name_remove_portfolio_coin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderhistory',
            name='order_date',
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='order_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
